### ISSUE TITLE
Feature request: Soundcloud Support

### ISSUE THREAD

**Issue by commodoor** [hmhrex/Grav-MusicCard#1]
It would be great if it's also could support soundcloud, or maybe it's own small plugin.

**Comment by hmhrex** [comment]
I will look into how this would work. It might be pretty easy to handle.

**Comment by hmhrex** [comment]
You can find the initial code in the SoundCloud branch.

**Comment by hmhrex** [comment]
SoundCloud is now supported as of v1.1
